### ISSUE TITLE
UX Improvement for Extreme Settings

### ISSUE THREAD

**Issue by Seirade** [FlashpointProject/launcher#240] opened 2021-09-04 07:22 UTC
**Is your feature request related to a problem? Please describe.**
The current state of communicating to the user how to show "extreme" content is confusing. By default, the extreme filters are not shown, and to enable the ability to see them, users have to toggle on an "Extreme Games" setting. This leads them to believe that once that setting is enabled, there is no further action needed. Furthermore, from observation of our help channels, it seems that people generally expect the feature of the filters to be an additive process, rather than subtractive.

**Describe the solution you'd like**
Scroll down for a picture showing the changes described below.

First, the labeling of the feature to show the filters should be rewritten to make it more obvious what it actually does, such as "Show Extreme Filters". As well, the description sub-heading should be placed under it like all the rest of the settings.

Secondly, the filters themselves, along with other settings related to extreme content, should be placed in their own settings group, to better organize them. The heading could be "Extreme Settings" or something more general like "Search Settings", since filters aren't exclusively extreme.

Third, the "(18)" icon should be displayed next to extreme filters. This would help draw better attention to filters that suddenly appeared when toggling their visibility, as it can be easy to miss.

Lastly (this is not a Launcher feature, but a note for project organization), the extreme filters should be disabled by default. It can be safely assumed that anyone toggling the visibility of extreme filters to ON is wanting to view said content, but the "double-safety" is a confusing UX design. Moreover, when the filters are hidden, extreme content is *also* hidden, regardless of a filter being enabled or disabled.

![Extreme Settings UX](https://user-images.githubusercontent.com/45798662/132086415-3fb1a277-f8fe-4f09-b0d9-dd9570b75359.png)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by colin969** [comment] 2021-09-17 10:31
> Moreover, when the filters are hidden, extreme content is also hidden, regardless of a filter being enabled or disabled.

This is by design, Extreme filters dictate what is meant to be hidden when Extreme content is disabled.

Most is this is addressed in 27b62e0

**Closed** 2021-09-22 23:03 UTC
Labels: enhancement
