### ISSUE TITLE
Is there a way to list all installed/previously played games?

### ISSUE THREAD

**Issue by ChildishGiant** [FlashpointProject/launcher#189] opened 2021-02-10 15:34 UTC
I'm scoured the ui but can't find any such option

**Comment by colin969** [comment] 2021-02-12 14:35
Not currently, no. Some people suggest adding them to a playlist.

**Comment by colin969** [comment] 2021-02-27 13:12
Duplicate of https://github.com/FlashpointProject/launcher/issues/171

**Closed by colin969** 2021-02-27 13:12 UTC
