### ISSUE TITLE
Error when running from non system drive

### ISSUE THREAD

**Issue by PhillScargill** [FlashpointProject/launcher#28] opened 2019-07-17 11:17 UTC
When running from a drive other than the one my OS is installed on I get this error

Error with proxy: Error reading original system proxy settings. Make sure you have registry read permission. Error code: 12178

And the flash player opens to a white screen on all games

Using Windows 10

**Comment by TBubba** [comment] 2019-07-20 02:01
Hi, and sorry for the late response.

Where does the error show up? In the launchers "Logs" tab, or in the log of the "Redirector"?

Do you get any other errors or related messages in the launchers "Logs" tab?

**Comment by TBubba** [comment] 2019-07-20 02:03
You could try running the launcher as an administrator.
The launcher executable is located at ``Flashpoint/Launcher/FlashpointLauncher.exe``.

**Comment by TBubba** [comment] 2019-10-07 20:29
Closing this for now, feel free to open it again

**Closed by TBubba** 2019-10-07 20:29 UTC

**Comment by obvious-burner** [comment] 2020-01-04 21:04
I can confirm that this isn't an isolated issue.
To fill some information in, it seems that the error pops up both in the Redirector's log as well as in a separate dialogue box. Running the launcher executable as an administrator doesn't seem to be a valid workaround either as it still causes the same problem. (Redirector logs error, Flash Player doesn't function properly)

**Comment by TBubba** [comment] 2020-01-06 01:42
I talked with some other people working on this and it turns out the Redirector (a separate program that comes with Flashpoint) can have trouble setting the system proxy for various reasons. I was told that antivirus programs could cause these sorts of issues.

You can check out our guide on antivirus interference, or ask someone who knows more about this on our discord channel.
Guide: https://bluemaxima.org/flashpoint/datahub/Troubleshooting_Antivirus_Interference
Discord: https://discordapp.com/invite/S9uJ794

**Comment by obvious-burner** [comment] 2020-01-07 14:13
I've tried both adding the entire directory as an exception as well as turning Malwarebytes off completely - still no dice, unfortunately, I doubt that's the antivirus causing problems here. Could we possibly get this reopened? It's not uncommon to have a configuration consisting of two (or more) separate system and data partitions. If that is indeed the case, it completely incapacitates Flashpoint.

**Comment by TBubba** [comment] 2020-01-08 01:17
A lot of people (including me) run Flashpoint on a different drive/partition from the OS without running into this problem, so something else must be behind this. Also the Redirector is a separate program that is not developed by us working on the launcher, so we're not that familiar with how it works internally (at least I'm not).

You're welcome to hop on our discord channel and ask someone on the team who is more knowledgeable about this! Or if you're familiar with C# you could look into it yourself, the source code for the Redirector can be found inside ``Flashpoint/FPSoftware/Redirector/Program.cs``.
